#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication setFields

runApplication decomposePar

#--runApplication will interogate the decomposeParDict to find the number of cores
#-- and run with this

mpirun -np 8 rhoCentralFoam -parallel


#------------------------------------------------------------------------------
